with-expecter: True
inpackage: true
dir: "{{.InterfaceDir}}"
mockname: "{{.InterfaceName}}Mock"
outpkg: "mocks"
filename: "{{.InterfaceName | lower }}_mock.go"
packages:
  github.com/DolusMockServer/dolus/internal/api:
    interfaces:
      Mapper:
  github.com/DolusMockServer/dolus/pkg/expectation/engine:
    interfaces:
      ExpectationEngine:
      RouteManager:
