// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/deepmap/oapi-codegen version v1.15.0 DO NOT EDIT.
package api

import (
	"bytes"
	"compress/gzip"
	"context"
	"encoding/base64"
	"encoding/json"
	"fmt"
	"io"
	"net/http"
	"net/url"
	"path"
	"strings"

	"github.com/getkin/kin-openapi/openapi3"
	"github.com/labstack/echo/v4"
	"github.com/oapi-codegen/runtime"
)

// Defines values for ExpectationTypeParameter.
const (
	ExpectationTypeParameterCUSTOM  ExpectationTypeParameter = "CUSTOM"
	ExpectationTypeParameterDEFAULT ExpectationTypeParameter = "DEFAULT"
)

// Defines values for MethodParameter.
const (
	MethodParameterCONNECT MethodParameter = "CONNECT"
	MethodParameterDELETE  MethodParameter = "DELETE"
	MethodParameterGET     MethodParameter = "GET"
	MethodParameterHEAD    MethodParameter = "HEAD"
	MethodParameterOPTIONS MethodParameter = "OPTIONS"
	MethodParameterPATCH   MethodParameter = "PATCH"
	MethodParameterPOST    MethodParameter = "POST"
	MethodParameterPUT     MethodParameter = "PUT"
	MethodParameterTRACE   MethodParameter = "TRACE"
)

// Defines values for GetExpectationsParamsExpectationType.
const (
	GetExpectationsParamsExpectationTypeCUSTOM  GetExpectationsParamsExpectationType = "CUSTOM"
	GetExpectationsParamsExpectationTypeDEFAULT GetExpectationsParamsExpectationType = "DEFAULT"
)

// Defines values for GetExpectationsParamsMethod.
const (
	GetExpectationsParamsMethodCONNECT GetExpectationsParamsMethod = "CONNECT"
	GetExpectationsParamsMethodDELETE  GetExpectationsParamsMethod = "DELETE"
	GetExpectationsParamsMethodGET     GetExpectationsParamsMethod = "GET"
	GetExpectationsParamsMethodHEAD    GetExpectationsParamsMethod = "HEAD"
	GetExpectationsParamsMethodOPTIONS GetExpectationsParamsMethod = "OPTIONS"
	GetExpectationsParamsMethodPATCH   GetExpectationsParamsMethod = "PATCH"
	GetExpectationsParamsMethodPOST    GetExpectationsParamsMethod = "POST"
	GetExpectationsParamsMethodPUT     GetExpectationsParamsMethod = "PUT"
	GetExpectationsParamsMethodTRACE   GetExpectationsParamsMethod = "TRACE"
)

// BadRequest defines model for BadRequest.
type BadRequest = ErrorResponseBody

// Callback Defines a callback that will be triggered by the mock server, specifying the HTTP method, request body, URL, and timeout.
type Callback struct {
	// HttpMethod The HTTP method used for the callback request (e.g., POST, GET).
	HttpMethod string `json:"httpMethod"`

	// RequestBody The body of the callback request.
	RequestBody *map[string]interface{} `json:"requestBody,omitempty"`

	// Timeout Wait time in milliseconds before the callback request is invoked.
	Timeout int `json:"timeout"`

	// Url The URL to which the callback request will be sent.
	Url string `json:"url"`
}

// ErrorResponseBody defines model for ErrorResponseBody.
type ErrorResponseBody struct {
	// Message message describing error that has occured
	Message string `json:"message"`
}

// Expectation Represents an expectation set in the mock server, including the priority, request details, response details, and optional callback configuration.
type Expectation struct {
	// Callback Defines a callback that will be triggered by the mock server, specifying the HTTP method, request body, URL, and timeout.
	Callback *Callback `json:"callback,omitempty"`

	// Priority The priority level of the expectation. Higher values indicate higher priority.
	Priority int `json:"priority"`

	// Request Details of the request that the mock server should match, including the path, HTTP method, and optional request body.
	Request Request `json:"request"`

	// Response Details of the response that the mock server should return, including the status code and optional response body.
	Response Response `json:"response"`
}

// Expectations A collection of expectations, each defining a request-response pair or callback configuration for the mock server.
type Expectations struct {
	// Expectations A list of expectation objects.
	Expectations []Expectation `json:"expectations"`
}

// InternalServerError defines model for InternalServerError.
type InternalServerError = ErrorResponseBody

// Request Details of the request that the mock server should match, including the path, HTTP method, and optional request body.
type Request struct {
	// Body Optional body of the request.
	Body *map[string]interface{} `json:"body,omitempty"`

	// Method The HTTP method of the request (e.g., GET, POST).
	Method string `json:"method"`

	// Path The path of the request to match.
	Path string `json:"path"`
}

// Response Details of the response that the mock server should return, including the status code and optional response body.
type Response struct {
	// Body Optional body of the response.
	Body *map[string]interface{} `json:"body,omitempty"`

	// Status The HTTP status code of the response.
	Status int `json:"status"`
}

// Route Represents a route defined in the mock server, including the path and the operation (HTTP method).
type Route struct {
	// Operation The HTTP method of the route (e.g., GET, POST).
	Operation string `json:"operation"`

	// Path The path of the route.
	Path string `json:"path"`
}

// ExpectationTypeParameter defines model for ExpectationTypeParameter.
type ExpectationTypeParameter string

// MethodParameter defines model for MethodParameter.
type MethodParameter string

// PathParameter defines model for PathParameter.
type PathParameter = string

// GetExpectationsParams defines parameters for GetExpectations.
type GetExpectationsParams struct {
	// ExpectationType Parameter specifying the type of expectation to return, can be either DEFAULT or CUSTOM.
	ExpectationType *GetExpectationsParamsExpectationType `form:"expectationType,omitempty" json:"expectationType,omitempty"`

	// Path Path of the expectation to filter by.
	Path *PathParameter `form:"path,omitempty" json:"path,omitempty"`

	// Method HTTP method of the expectation to filter by.
	Method *GetExpectationsParamsMethod `form:"method,omitempty" json:"method,omitempty"`
}

// GetExpectationsParamsExpectationType defines parameters for GetExpectations.
type GetExpectationsParamsExpectationType string

// GetExpectationsParamsMethod defines parameters for GetExpectations.
type GetExpectationsParamsMethod string

// GetLogsParams defines parameters for GetLogs.
type GetLogsParams struct {
	// Lines number of log lines to return
	Lines *int `form:"lines,omitempty" json:"lines,omitempty"`
}

// CreateExpectationJSONRequestBody defines body for CreateExpectation for application/json ContentType.
type CreateExpectationJSONRequestBody = Expectation

// RequestEditorFn  is the function signature for the RequestEditor callback function
type RequestEditorFn func(ctx context.Context, req *http.Request) error

// Doer performs HTTP requests.
//
// The standard http.Client implements this interface.
type HttpRequestDoer interface {
	Do(req *http.Request) (*http.Response, error)
}

// Client which conforms to the OpenAPI3 specification for this service.
type Client struct {
	// The endpoint of the server conforming to this interface, with scheme,
	// https://api.deepmap.com for example. This can contain a path relative
	// to the server, such as https://api.deepmap.com/dev-test, and all the
	// paths in the swagger spec will be appended to the server.
	Server string

	// Doer for performing requests, typically a *http.Client with any
	// customized settings, such as certificate chains.
	Client HttpRequestDoer

	// A list of callbacks for modifying requests which are generated before sending over
	// the network.
	RequestEditors []RequestEditorFn
}

// ClientOption allows setting custom parameters during construction
type ClientOption func(*Client) error

// Creates a new Client, with reasonable defaults
func NewClient(server string, opts ...ClientOption) (*Client, error) {
	// create a client with sane default values
	client := Client{
		Server: server,
	}
	// mutate client and add all optional params
	for _, o := range opts {
		if err := o(&client); err != nil {
			return nil, err
		}
	}
	// ensure the server URL always has a trailing slash
	if !strings.HasSuffix(client.Server, "/") {
		client.Server += "/"
	}
	// create httpClient, if not already present
	if client.Client == nil {
		client.Client = &http.Client{}
	}
	return &client, nil
}

// WithHTTPClient allows overriding the default Doer, which is
// automatically created using http.Client. This is useful for tests.
func WithHTTPClient(doer HttpRequestDoer) ClientOption {
	return func(c *Client) error {
		c.Client = doer
		return nil
	}
}

// WithRequestEditorFn allows setting up a callback function, which will be
// called right before sending the request. This can be used to mutate the request.
func WithRequestEditorFn(fn RequestEditorFn) ClientOption {
	return func(c *Client) error {
		c.RequestEditors = append(c.RequestEditors, fn)
		return nil
	}
}

// The interface specification for the client above.
type ClientInterface interface {
	// GetExpectations request
	GetExpectations(ctx context.Context, params *GetExpectationsParams, reqEditors ...RequestEditorFn) (*http.Response, error)

	// CreateExpectationWithBody request with any body
	CreateExpectationWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error)

	CreateExpectation(ctx context.Context, body CreateExpectationJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error)

	// GetLogs request
	GetLogs(ctx context.Context, params *GetLogsParams, reqEditors ...RequestEditorFn) (*http.Response, error)

	// GetRoutes request
	GetRoutes(ctx context.Context, reqEditors ...RequestEditorFn) (*http.Response, error)
}

func (c *Client) GetExpectations(ctx context.Context, params *GetExpectationsParams, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewGetExpectationsRequest(c.Server, params)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) CreateExpectationWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewCreateExpectationRequestWithBody(c.Server, contentType, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) CreateExpectation(ctx context.Context, body CreateExpectationJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewCreateExpectationRequest(c.Server, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) GetLogs(ctx context.Context, params *GetLogsParams, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewGetLogsRequest(c.Server, params)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) GetRoutes(ctx context.Context, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewGetRoutesRequest(c.Server)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

// NewGetExpectationsRequest generates requests for GetExpectations
func NewGetExpectationsRequest(server string, params *GetExpectationsParams) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/v1/dolus/expectations")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	if params != nil {
		queryValues := queryURL.Query()

		if params.ExpectationType != nil {

			if queryFrag, err := runtime.StyleParamWithLocation("form", true, "expectationType", runtime.ParamLocationQuery, *params.ExpectationType); err != nil {
				return nil, err
			} else if parsed, err := url.ParseQuery(queryFrag); err != nil {
				return nil, err
			} else {
				for k, v := range parsed {
					for _, v2 := range v {
						queryValues.Add(k, v2)
					}
				}
			}

		}

		if params.Path != nil {

			if queryFrag, err := runtime.StyleParamWithLocation("form", true, "path", runtime.ParamLocationQuery, *params.Path); err != nil {
				return nil, err
			} else if parsed, err := url.ParseQuery(queryFrag); err != nil {
				return nil, err
			} else {
				for k, v := range parsed {
					for _, v2 := range v {
						queryValues.Add(k, v2)
					}
				}
			}

		}

		if params.Method != nil {

			if queryFrag, err := runtime.StyleParamWithLocation("form", true, "method", runtime.ParamLocationQuery, *params.Method); err != nil {
				return nil, err
			} else if parsed, err := url.ParseQuery(queryFrag); err != nil {
				return nil, err
			} else {
				for k, v := range parsed {
					for _, v2 := range v {
						queryValues.Add(k, v2)
					}
				}
			}

		}

		queryURL.RawQuery = queryValues.Encode()
	}

	req, err := http.NewRequest("GET", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewCreateExpectationRequest calls the generic CreateExpectation builder with application/json body
func NewCreateExpectationRequest(server string, body CreateExpectationJSONRequestBody) (*http.Request, error) {
	var bodyReader io.Reader
	buf, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	bodyReader = bytes.NewReader(buf)
	return NewCreateExpectationRequestWithBody(server, "application/json", bodyReader)
}

// NewCreateExpectationRequestWithBody generates requests for CreateExpectation with any type of body
func NewCreateExpectationRequestWithBody(server string, contentType string, body io.Reader) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/v1/dolus/expectations")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("POST", queryURL.String(), body)
	if err != nil {
		return nil, err
	}

	req.Header.Add("Content-Type", contentType)

	return req, nil
}

// NewGetLogsRequest generates requests for GetLogs
func NewGetLogsRequest(server string, params *GetLogsParams) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/v1/dolus/logs")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	if params != nil {
		queryValues := queryURL.Query()

		if params.Lines != nil {

			if queryFrag, err := runtime.StyleParamWithLocation("form", true, "lines", runtime.ParamLocationQuery, *params.Lines); err != nil {
				return nil, err
			} else if parsed, err := url.ParseQuery(queryFrag); err != nil {
				return nil, err
			} else {
				for k, v := range parsed {
					for _, v2 := range v {
						queryValues.Add(k, v2)
					}
				}
			}

		}

		queryURL.RawQuery = queryValues.Encode()
	}

	req, err := http.NewRequest("GET", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewGetRoutesRequest generates requests for GetRoutes
func NewGetRoutesRequest(server string) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/v1/dolus/routes")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("GET", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

func (c *Client) applyEditors(ctx context.Context, req *http.Request, additionalEditors []RequestEditorFn) error {
	for _, r := range c.RequestEditors {
		if err := r(ctx, req); err != nil {
			return err
		}
	}
	for _, r := range additionalEditors {
		if err := r(ctx, req); err != nil {
			return err
		}
	}
	return nil
}

// ClientWithResponses builds on ClientInterface to offer response payloads
type ClientWithResponses struct {
	ClientInterface
}

// NewClientWithResponses creates a new ClientWithResponses, which wraps
// Client with return type handling
func NewClientWithResponses(server string, opts ...ClientOption) (*ClientWithResponses, error) {
	client, err := NewClient(server, opts...)
	if err != nil {
		return nil, err
	}
	return &ClientWithResponses{client}, nil
}

// WithBaseURL overrides the baseURL.
func WithBaseURL(baseURL string) ClientOption {
	return func(c *Client) error {
		newBaseURL, err := url.Parse(baseURL)
		if err != nil {
			return err
		}
		c.Server = newBaseURL.String()
		return nil
	}
}

// ClientWithResponsesInterface is the interface specification for the client with responses above.
type ClientWithResponsesInterface interface {
	// GetExpectationsWithResponse request
	GetExpectationsWithResponse(ctx context.Context, params *GetExpectationsParams, reqEditors ...RequestEditorFn) (*GetExpectationsResponse, error)

	// CreateExpectationWithBodyWithResponse request with any body
	CreateExpectationWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*CreateExpectationResponse, error)

	CreateExpectationWithResponse(ctx context.Context, body CreateExpectationJSONRequestBody, reqEditors ...RequestEditorFn) (*CreateExpectationResponse, error)

	// GetLogsWithResponse request
	GetLogsWithResponse(ctx context.Context, params *GetLogsParams, reqEditors ...RequestEditorFn) (*GetLogsResponse, error)

	// GetRoutesWithResponse request
	GetRoutesWithResponse(ctx context.Context, reqEditors ...RequestEditorFn) (*GetRoutesResponse, error)
}

type GetExpectationsResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *Expectations
	JSON400      *BadRequest
	JSON500      *InternalServerError
}

// Status returns HTTPResponse.Status
func (r GetExpectationsResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r GetExpectationsResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type CreateExpectationResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON201      *Expectation
	JSON400      *BadRequest
	JSON500      *InternalServerError
}

// Status returns HTTPResponse.Status
func (r CreateExpectationResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r CreateExpectationResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type GetLogsResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON400      *BadRequest
	JSON500      *InternalServerError
}

// Status returns HTTPResponse.Status
func (r GetLogsResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r GetLogsResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type GetRoutesResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *[]Route
	JSON500      *InternalServerError
}

// Status returns HTTPResponse.Status
func (r GetRoutesResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r GetRoutesResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// GetExpectationsWithResponse request returning *GetExpectationsResponse
func (c *ClientWithResponses) GetExpectationsWithResponse(ctx context.Context, params *GetExpectationsParams, reqEditors ...RequestEditorFn) (*GetExpectationsResponse, error) {
	rsp, err := c.GetExpectations(ctx, params, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseGetExpectationsResponse(rsp)
}

// CreateExpectationWithBodyWithResponse request with arbitrary body returning *CreateExpectationResponse
func (c *ClientWithResponses) CreateExpectationWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*CreateExpectationResponse, error) {
	rsp, err := c.CreateExpectationWithBody(ctx, contentType, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseCreateExpectationResponse(rsp)
}

func (c *ClientWithResponses) CreateExpectationWithResponse(ctx context.Context, body CreateExpectationJSONRequestBody, reqEditors ...RequestEditorFn) (*CreateExpectationResponse, error) {
	rsp, err := c.CreateExpectation(ctx, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseCreateExpectationResponse(rsp)
}

// GetLogsWithResponse request returning *GetLogsResponse
func (c *ClientWithResponses) GetLogsWithResponse(ctx context.Context, params *GetLogsParams, reqEditors ...RequestEditorFn) (*GetLogsResponse, error) {
	rsp, err := c.GetLogs(ctx, params, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseGetLogsResponse(rsp)
}

// GetRoutesWithResponse request returning *GetRoutesResponse
func (c *ClientWithResponses) GetRoutesWithResponse(ctx context.Context, reqEditors ...RequestEditorFn) (*GetRoutesResponse, error) {
	rsp, err := c.GetRoutes(ctx, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseGetRoutesResponse(rsp)
}

// ParseGetExpectationsResponse parses an HTTP response from a GetExpectationsWithResponse call
func ParseGetExpectationsResponse(rsp *http.Response) (*GetExpectationsResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &GetExpectationsResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest Expectations
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 400:
		var dest BadRequest
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON400 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 500:
		var dest InternalServerError
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON500 = &dest

	}

	return response, nil
}

// ParseCreateExpectationResponse parses an HTTP response from a CreateExpectationWithResponse call
func ParseCreateExpectationResponse(rsp *http.Response) (*CreateExpectationResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &CreateExpectationResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 201:
		var dest Expectation
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON201 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 400:
		var dest BadRequest
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON400 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 500:
		var dest InternalServerError
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON500 = &dest

	}

	return response, nil
}

// ParseGetLogsResponse parses an HTTP response from a GetLogsWithResponse call
func ParseGetLogsResponse(rsp *http.Response) (*GetLogsResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &GetLogsResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 400:
		var dest BadRequest
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON400 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 500:
		var dest InternalServerError
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON500 = &dest

	}

	return response, nil
}

// ParseGetRoutesResponse parses an HTTP response from a GetRoutesWithResponse call
func ParseGetRoutesResponse(rsp *http.Response) (*GetRoutesResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &GetRoutesResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest []Route
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 500:
		var dest InternalServerError
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON500 = &dest

	}

	return response, nil
}

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// Retrieve all expectations
	// (GET /v1/dolus/expectations)
	GetExpectations(ctx echo.Context, params GetExpectationsParams) error
	// Create a new expectation
	// (POST /v1/dolus/expectations)
	CreateExpectation(ctx echo.Context) error
	// Retrieve the mock server logs
	// (GET /v1/dolus/logs)
	GetLogs(ctx echo.Context, params GetLogsParams) error
	// Retrieve all mock server routes
	// (GET /v1/dolus/routes)
	GetRoutes(ctx echo.Context) error
}

// ServerInterfaceWrapper converts echo contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler ServerInterface
}

// GetExpectations converts echo context to params.
func (w *ServerInterfaceWrapper) GetExpectations(ctx echo.Context) error {
	var err error

	// Parameter object where we will unmarshal all parameters from the context
	var params GetExpectationsParams
	// ------------- Optional query parameter "expectationType" -------------

	err = runtime.BindQueryParameter("form", true, false, "expectationType", ctx.QueryParams(), &params.ExpectationType)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter expectationType: %s", err))
	}

	// ------------- Optional query parameter "path" -------------

	err = runtime.BindQueryParameter("form", true, false, "path", ctx.QueryParams(), &params.Path)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter path: %s", err))
	}

	// ------------- Optional query parameter "method" -------------

	err = runtime.BindQueryParameter("form", true, false, "method", ctx.QueryParams(), &params.Method)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter method: %s", err))
	}

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.GetExpectations(ctx, params)
	return err
}

// CreateExpectation converts echo context to params.
func (w *ServerInterfaceWrapper) CreateExpectation(ctx echo.Context) error {
	var err error

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.CreateExpectation(ctx)
	return err
}

// GetLogs converts echo context to params.
func (w *ServerInterfaceWrapper) GetLogs(ctx echo.Context) error {
	var err error

	// Parameter object where we will unmarshal all parameters from the context
	var params GetLogsParams
	// ------------- Optional query parameter "lines" -------------

	err = runtime.BindQueryParameter("form", true, false, "lines", ctx.QueryParams(), &params.Lines)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter lines: %s", err))
	}

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.GetLogs(ctx, params)
	return err
}

// GetRoutes converts echo context to params.
func (w *ServerInterfaceWrapper) GetRoutes(ctx echo.Context) error {
	var err error

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.GetRoutes(ctx)
	return err
}

// This is a simple interface which specifies echo.Route addition functions which
// are present on both echo.Echo and echo.Group, since we want to allow using
// either of them for path registration
type EchoRouter interface {
	CONNECT(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	DELETE(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	GET(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	HEAD(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	OPTIONS(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	PATCH(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	POST(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	PUT(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	TRACE(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
}

// RegisterHandlers adds each server route to the EchoRouter.
func RegisterHandlers(router EchoRouter, si ServerInterface) {
	RegisterHandlersWithBaseURL(router, si, "")
}

// Registers handlers, and prepends BaseURL to the paths, so that the paths
// can be served under a prefix.
func RegisterHandlersWithBaseURL(router EchoRouter, si ServerInterface, baseURL string) {

	wrapper := ServerInterfaceWrapper{
		Handler: si,
	}

	router.GET(baseURL+"/v1/dolus/expectations", wrapper.GetExpectations)
	router.POST(baseURL+"/v1/dolus/expectations", wrapper.CreateExpectation)
	router.GET(baseURL+"/v1/dolus/logs", wrapper.GetLogs)
	router.GET(baseURL+"/v1/dolus/routes", wrapper.GetRoutes)

}

// Base64 encoded, gzipped, json marshaled Swagger object
var swaggerSpec = []string{

	"H4sIAAAAAAAC/+xZTW/jOBL9KwR3DjOAxnJ6ZoCFTptOPJ1gk06QONhDbw40VZY4oUg1SSUxBv7viyIl",
	"6zO2Zzd7aKAv3RFFFauKr1490n9SrotSK1DO0uRPWjLDCnBg/NPitQTumBNaLTcl3DYv8V0KlhtR4jua",
	"0N0rYkvgYr0RKiMuB+I2JRC9JtCaIk4TA64yKiKcKbICAsLlYMj54vfTh6sl0YacPdwvb65nNKIC7X+t",
	"wGxoRBUrgCYU+o7RiFqeQ8HQMVBVQZMvtDZGIxps0ceIojc0odYZoTK63Ub0Glyu0z2RXSyXt6TwszAO",
	"jGkQy1pIDHy1ecvb8PWkk58W6ODtzT3+d7E4PcenBz92ujy7oBFd3p2eLTCIm8+fF2f45uZ2eXnz+Z5G",
	"9HxxtVgupgO7ZS7fu2Eu/2/jKZnLe9EMV982Lz2KPrL0Dr5WYJ1HmNElGCfAvyvAWpbB2L/6BQmjK4QT",
	"GKMNcTlzJGeWaM4rA5jWcfAGvlYCXyZfdktgloSTOHOBlu7AllpZ+KjTTWtEr/4A7ug2omdMyhXjT2Pf",
	"zmEtFFjCCK/nBK9ehJSIZmdEloGBlKw2PsGF5k/EgnkGEw0LpIOviJiQJ7LS6SYiD3dXEWEqJU4UoCuH",
	"+9FPX+5cGRA89nLZN04qCylZ+wxC63iz4o8wy2YRQSRG5NNi+dNsnNiQV7DOp2xyQXS8gdVwjdlUluvQ",
	"xtb+xYTzgROhSCGkFBa4VqklK1hrA9NhCEuEetZPkHZWE8pBBgaXq4ycdvzh7gqx/5ILnk+bbnbXgnKz",
	"g6jr7ExYtQ21A8QdxiYyMwbpt1Q9ndYxdu8OSgOYR0uY6tGPBYf7PSoaobis0qZmSiO0EW7TFkwKjglp",
	"cSD41Y5gAWm/MpPtrnKt1iKrjF92XFi8U/w/GFjThP4tbltlXNNbvNvALVoIXk0DrHlLJDyDnKDeGbkQ",
	"GXbBZyYrQByngjMHJA/DjYFpYJuWYff52xCx/yJk6vAn9bwhNHbxtqt3rD4OQRHR15/hlRWlhFpc+L/J",
	"ST/fqpKym8t5L7aVr4Mwp26rSd1EfVdKaGydNhBrk4KJPwwDXdV1hHFKcEATZyqIaAnu0nOo8P/+kGpZ",
	"eS8ds0+4BKhL5X7x9gr2SpOTeUQLbI5z3+0cczifZlqnJGUb2hn8MJ9vfU/s1IQdg+SUcC0lcF8HfcVk",
	"IwKM5yTFxoNFwBrg/7zDe8mEQeE0jfAd8Xeqaox6OOCgFNYNxVzYXeu1goPCHoJTlxi2O4wwYzBpA4T1",
	"/OkyUHd8gnwulQOjmLz3cXq++qbIsyOXhsrDk1rDHg37eccGu0tsriuZkoI5no8IlLk86kuPHk12dcgY",
	"JqvJ9n/TfNzVAPtaf3GkcBkEWyuVT4tlkCvTSiWwwSQRd5TvLoE65OlwX6+1b+17Z2PvdhQ4sZ0tAR3Y",
	"z7qY921oc3Tq72ggG8J1CsOtrG2+w14GS7N/q6koG7p7czu7Lg5NTvS0QeJr872M12mdSrmuHOwXHsTg",
	"nMCpkB6jOhA4Xo7nQDCHgQB/7GD1p3GCdxOPB7r3611hjhaPxnbrcTfZPqGjTKMJodY69FTlGPesBQUT",
	"kibUt9EPv/36jwwHZlwX7Sny9PaS3FdlqY2rJXLiVbNN4jgTLq9WOD8+RxPXmj8FMo9DZ95Go5CFJWiS",
	"SalfLNnoKlS1Qirv91KfjloZSp1Z3xzZsDVKwaEu2trj68sluapHhx7rEpTVleEw0yaL649tfH25DMec",
	"kMbgfUSfwdjg+MlsjhPwe1YKmtBfZjgUttYjKH4+CVHHw/6cwUSP+B0cz/3ptGnXTErCK2NAuV4m3lTb",
	"DXnITX0ZUB9lNyVEde/A3AXYzrqQufR6DNygQ3evlb5M64N2SvzmtdM2Ovht/9rjiA+GF0Dbx1Yx+iR/",
	"mM8bdIPy+WZlKVGaC63iP2yo7PYy5EjxY0PxDHj3n4iFX99xxc7ly8R6H1lKOkeC395x4SkNNuFBM42E",
	"eaSZGFFbFQUzG8/azgh4Bg9kGGg/ltmxVERm1FMC6jRNsTIUvAxvvUZFsBPbuX4JLXbQhhEjKX4abnQE",
	"b+SEHZfEmQHmoKt9R5cp7w0wGg4dAyyf/L+WGm5siDj9jucxnkNqxjB8G87bqNMFsGUdZH8EbOhtRhd7",
	"GV6KQjjwQGYNlCElqipWYLB9SJ0RKRR2TKdJDrLEppHCqsoyfxjFVqCVcBpVxWQ7uEKXR22g7/nEgu0v",
	"BW/cRPtZU1fRrYo8TOcOXl1cSiYGaJiQOt/Z+i+w9fD8IgMIGoj7xwG0gzL7i9ImfNQoHLnZK+lLo5+F",
	"l/QoW00R+J+tdOV2It/WJ6gaxJbYIFNhWuvcBaf/R9lw1OVJUOHja5M3oPkt9PMuQkyTyQYj9cBj+EnJ",
	"TwrU0YrvJI6l5kzm2rrkZP73uVdwtYHxuXa3pwYkq2nPHxL8NU9XHI/RM/n7o/Ui85hlGOdg7Y4xm0Un",
	"SqRhN3w61roJSd1rfpffeoH6efu4/U8AAAD//7dWlpQIHgAA",
}

// GetSwagger returns the content of the embedded swagger specification file
// or error if failed to decode
func decodeSpec() ([]byte, error) {
	zipped, err := base64.StdEncoding.DecodeString(strings.Join(swaggerSpec, ""))
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr, err := gzip.NewReader(bytes.NewReader(zipped))
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}
	var buf bytes.Buffer
	_, err = buf.ReadFrom(zr)
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cached of a decoded swagger spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSwagger returns the Swagger specification corresponding to the generated code
// in this file. The external references of Swagger specification are resolved.
// The logic of resolving external references is tightly connected to "import-mapping" feature.
// Externally referenced files must be embedded in the corresponding golang packages.
// Urls can be supported but this task was out of the scope.
func GetSwagger() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}
