// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/deepmap/oapi-codegen version v1.15.0 DO NOT EDIT.
package api

import (
	"bytes"
	"compress/gzip"
	"context"
	"encoding/base64"
	"encoding/json"
	"fmt"
	"io"
	"net/http"
	"net/url"
	"path"
	"strings"

	"github.com/getkin/kin-openapi/openapi3"
	"github.com/labstack/echo/v4"
	"github.com/oapi-codegen/runtime"
)

// Defines values for ExpectationTypeParameter.
const (
	ExpectationTypeParameterCUSTOM  ExpectationTypeParameter = "CUSTOM"
	ExpectationTypeParameterDEFAULT ExpectationTypeParameter = "DEFAULT"
)

// Defines values for MethodParameter.
const (
	MethodParameterCONNECT MethodParameter = "CONNECT"
	MethodParameterDELETE  MethodParameter = "DELETE"
	MethodParameterGET     MethodParameter = "GET"
	MethodParameterHEAD    MethodParameter = "HEAD"
	MethodParameterOPTIONS MethodParameter = "OPTIONS"
	MethodParameterPATCH   MethodParameter = "PATCH"
	MethodParameterPOST    MethodParameter = "POST"
	MethodParameterPUT     MethodParameter = "PUT"
	MethodParameterTRACE   MethodParameter = "TRACE"
)

// Defines values for GetExpectationsParamsExpectationType.
const (
	GetExpectationsParamsExpectationTypeCUSTOM  GetExpectationsParamsExpectationType = "CUSTOM"
	GetExpectationsParamsExpectationTypeDEFAULT GetExpectationsParamsExpectationType = "DEFAULT"
)

// Defines values for GetExpectationsParamsMethod.
const (
	GetExpectationsParamsMethodCONNECT GetExpectationsParamsMethod = "CONNECT"
	GetExpectationsParamsMethodDELETE  GetExpectationsParamsMethod = "DELETE"
	GetExpectationsParamsMethodGET     GetExpectationsParamsMethod = "GET"
	GetExpectationsParamsMethodHEAD    GetExpectationsParamsMethod = "HEAD"
	GetExpectationsParamsMethodOPTIONS GetExpectationsParamsMethod = "OPTIONS"
	GetExpectationsParamsMethodPATCH   GetExpectationsParamsMethod = "PATCH"
	GetExpectationsParamsMethodPOST    GetExpectationsParamsMethod = "POST"
	GetExpectationsParamsMethodPUT     GetExpectationsParamsMethod = "PUT"
	GetExpectationsParamsMethodTRACE   GetExpectationsParamsMethod = "TRACE"
)

// BadRequest defines model for BadRequest.
type BadRequest = ErrorResponseBody

// Callback Defines a callback that will be triggered by the mock server, specifying the HTTP method, request body, URL, and timeout.
type Callback struct {
	// HttpMethod The HTTP method used for the callback request (e.g., POST, GET).
	HttpMethod string `json:"httpMethod"`

	// RequestBody The body of the callback request.
	RequestBody *map[string]interface{} `json:"requestBody,omitempty"`

	// Timeout Wait time in milliseconds before the callback request is invoked.
	Timeout int `json:"timeout"`

	// Url The URL to which the callback request will be sent.
	Url string `json:"url"`
}

// ErrorResponseBody defines model for ErrorResponseBody.
type ErrorResponseBody struct {
	// Message message describing error that has occurred
	Message string `json:"message"`
}

// Expectation Represents an expectation set in the mock server, including the priority, request details, response details, and optional callback configuration.
type Expectation struct {
	// Callback Defines a callback that will be triggered by the mock server, specifying the HTTP method, request body, URL, and timeout.
	Callback *Callback `json:"callback,omitempty"`

	// Priority The priority level of the expectation. Higher values indicate higher priority.
	Priority int `json:"priority"`

	// Request Details of the request that the mock server should match, including the path, HTTP method, and optional request body.
	Request Request `json:"request"`

	// Response Details of the response that the mock server should return, including the status code and optional response body.
	Response Response `json:"response"`
}

// Expectations A collection of expectations, each defining a request-response pair or callback configuration for the mock server.
type Expectations struct {
	// Expectations A list of expectation objects.
	Expectations []Expectation `json:"expectations"`
}

// InternalServerError defines model for InternalServerError.
type InternalServerError = ErrorResponseBody

// Request Details of the request that the mock server should match, including the path, HTTP method, and optional request body.
type Request struct {
	// Body Optional body of the request.
	Body *map[string]interface{} `json:"body,omitempty"`

	// Method The HTTP method of the request (e.g., GET, POST).
	Method string `json:"method"`

	// Path The path of the request to match.
	Path string `json:"path"`
}

// Response Details of the response that the mock server should return, including the status code and optional response body.
type Response struct {
	// Body Optional body of the response.
	Body *map[string]interface{} `json:"body,omitempty"`

	// Status The HTTP status code of the response.
	Status int `json:"status"`
}

// Route Represents a route defined in the mock server, including the path and the operation (HTTP method).
type Route struct {
	// Operation The HTTP method of the route (e.g., GET, POST).
	Operation string `json:"operation"`

	// Path The path of the route.
	Path string `json:"path"`
}

// ExpectationTypeParameter defines model for ExpectationTypeParameter.
type ExpectationTypeParameter string

// MethodParameter defines model for MethodParameter.
type MethodParameter string

// PathParameter defines model for PathParameter.
type PathParameter = string

// GetExpectationsParams defines parameters for GetExpectations.
type GetExpectationsParams struct {
	// ExpectationType Parameter specifying the type of expectation to return, can be either DEFAULT or CUSTOM.
	ExpectationType *GetExpectationsParamsExpectationType `form:"expectationType,omitempty" json:"expectationType,omitempty"`

	// Path Path of the expectation to filter by.
	Path *PathParameter `form:"path,omitempty" json:"path,omitempty"`

	// Method HTTP method of the expectation to filter by.
	Method *GetExpectationsParamsMethod `form:"method,omitempty" json:"method,omitempty"`
}

// GetExpectationsParamsExpectationType defines parameters for GetExpectations.
type GetExpectationsParamsExpectationType string

// GetExpectationsParamsMethod defines parameters for GetExpectations.
type GetExpectationsParamsMethod string

// GetLogsParams defines parameters for GetLogs.
type GetLogsParams struct {
	// Lines number of log lines to return
	Lines *int `form:"lines,omitempty" json:"lines,omitempty"`
}

// CreateExpectationJSONRequestBody defines body for CreateExpectation for application/json ContentType.
type CreateExpectationJSONRequestBody = Expectation

// RequestEditorFn  is the function signature for the RequestEditor callback function
type RequestEditorFn func(ctx context.Context, req *http.Request) error

// Doer performs HTTP requests.
//
// The standard http.Client implements this interface.
type HttpRequestDoer interface {
	Do(req *http.Request) (*http.Response, error)
}

// Client which conforms to the OpenAPI3 specification for this service.
type Client struct {
	// The endpoint of the server conforming to this interface, with scheme,
	// https://api.deepmap.com for example. This can contain a path relative
	// to the server, such as https://api.deepmap.com/dev-test, and all the
	// paths in the swagger spec will be appended to the server.
	Server string

	// Doer for performing requests, typically a *http.Client with any
	// customized settings, such as certificate chains.
	Client HttpRequestDoer

	// A list of callbacks for modifying requests which are generated before sending over
	// the network.
	RequestEditors []RequestEditorFn
}

// ClientOption allows setting custom parameters during construction
type ClientOption func(*Client) error

// Creates a new Client, with reasonable defaults
func NewClient(server string, opts ...ClientOption) (*Client, error) {
	// create a client with sane default values
	client := Client{
		Server: server,
	}
	// mutate client and add all optional params
	for _, o := range opts {
		if err := o(&client); err != nil {
			return nil, err
		}
	}
	// ensure the server URL always has a trailing slash
	if !strings.HasSuffix(client.Server, "/") {
		client.Server += "/"
	}
	// create httpClient, if not already present
	if client.Client == nil {
		client.Client = &http.Client{}
	}
	return &client, nil
}

// WithHTTPClient allows overriding the default Doer, which is
// automatically created using http.Client. This is useful for tests.
func WithHTTPClient(doer HttpRequestDoer) ClientOption {
	return func(c *Client) error {
		c.Client = doer
		return nil
	}
}

// WithRequestEditorFn allows setting up a callback function, which will be
// called right before sending the request. This can be used to mutate the request.
func WithRequestEditorFn(fn RequestEditorFn) ClientOption {
	return func(c *Client) error {
		c.RequestEditors = append(c.RequestEditors, fn)
		return nil
	}
}

// The interface specification for the client above.
type ClientInterface interface {
	// GetExpectations request
	GetExpectations(ctx context.Context, params *GetExpectationsParams, reqEditors ...RequestEditorFn) (*http.Response, error)

	// CreateExpectationWithBody request with any body
	CreateExpectationWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error)

	CreateExpectation(ctx context.Context, body CreateExpectationJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error)

	// GetLogs request
	GetLogs(ctx context.Context, params *GetLogsParams, reqEditors ...RequestEditorFn) (*http.Response, error)

	// GetRoutes request
	GetRoutes(ctx context.Context, reqEditors ...RequestEditorFn) (*http.Response, error)
}

func (c *Client) GetExpectations(ctx context.Context, params *GetExpectationsParams, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewGetExpectationsRequest(c.Server, params)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) CreateExpectationWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewCreateExpectationRequestWithBody(c.Server, contentType, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) CreateExpectation(ctx context.Context, body CreateExpectationJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewCreateExpectationRequest(c.Server, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) GetLogs(ctx context.Context, params *GetLogsParams, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewGetLogsRequest(c.Server, params)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) GetRoutes(ctx context.Context, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewGetRoutesRequest(c.Server)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

// NewGetExpectationsRequest generates requests for GetExpectations
func NewGetExpectationsRequest(server string, params *GetExpectationsParams) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/v1/dolus/expectations")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	if params != nil {
		queryValues := queryURL.Query()

		if params.ExpectationType != nil {

			if queryFrag, err := runtime.StyleParamWithLocation("form", true, "expectationType", runtime.ParamLocationQuery, *params.ExpectationType); err != nil {
				return nil, err
			} else if parsed, err := url.ParseQuery(queryFrag); err != nil {
				return nil, err
			} else {
				for k, v := range parsed {
					for _, v2 := range v {
						queryValues.Add(k, v2)
					}
				}
			}

		}

		if params.Path != nil {

			if queryFrag, err := runtime.StyleParamWithLocation("form", true, "path", runtime.ParamLocationQuery, *params.Path); err != nil {
				return nil, err
			} else if parsed, err := url.ParseQuery(queryFrag); err != nil {
				return nil, err
			} else {
				for k, v := range parsed {
					for _, v2 := range v {
						queryValues.Add(k, v2)
					}
				}
			}

		}

		if params.Method != nil {

			if queryFrag, err := runtime.StyleParamWithLocation("form", true, "method", runtime.ParamLocationQuery, *params.Method); err != nil {
				return nil, err
			} else if parsed, err := url.ParseQuery(queryFrag); err != nil {
				return nil, err
			} else {
				for k, v := range parsed {
					for _, v2 := range v {
						queryValues.Add(k, v2)
					}
				}
			}

		}

		queryURL.RawQuery = queryValues.Encode()
	}

	req, err := http.NewRequest("GET", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewCreateExpectationRequest calls the generic CreateExpectation builder with application/json body
func NewCreateExpectationRequest(server string, body CreateExpectationJSONRequestBody) (*http.Request, error) {
	var bodyReader io.Reader
	buf, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	bodyReader = bytes.NewReader(buf)
	return NewCreateExpectationRequestWithBody(server, "application/json", bodyReader)
}

// NewCreateExpectationRequestWithBody generates requests for CreateExpectation with any type of body
func NewCreateExpectationRequestWithBody(server string, contentType string, body io.Reader) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/v1/dolus/expectations")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("POST", queryURL.String(), body)
	if err != nil {
		return nil, err
	}

	req.Header.Add("Content-Type", contentType)

	return req, nil
}

// NewGetLogsRequest generates requests for GetLogs
func NewGetLogsRequest(server string, params *GetLogsParams) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/v1/dolus/logs")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	if params != nil {
		queryValues := queryURL.Query()

		if params.Lines != nil {

			if queryFrag, err := runtime.StyleParamWithLocation("form", true, "lines", runtime.ParamLocationQuery, *params.Lines); err != nil {
				return nil, err
			} else if parsed, err := url.ParseQuery(queryFrag); err != nil {
				return nil, err
			} else {
				for k, v := range parsed {
					for _, v2 := range v {
						queryValues.Add(k, v2)
					}
				}
			}

		}

		queryURL.RawQuery = queryValues.Encode()
	}

	req, err := http.NewRequest("GET", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewGetRoutesRequest generates requests for GetRoutes
func NewGetRoutesRequest(server string) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/v1/dolus/routes")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("GET", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

func (c *Client) applyEditors(ctx context.Context, req *http.Request, additionalEditors []RequestEditorFn) error {
	for _, r := range c.RequestEditors {
		if err := r(ctx, req); err != nil {
			return err
		}
	}
	for _, r := range additionalEditors {
		if err := r(ctx, req); err != nil {
			return err
		}
	}
	return nil
}

// ClientWithResponses builds on ClientInterface to offer response payloads
type ClientWithResponses struct {
	ClientInterface
}

// NewClientWithResponses creates a new ClientWithResponses, which wraps
// Client with return type handling
func NewClientWithResponses(server string, opts ...ClientOption) (*ClientWithResponses, error) {
	client, err := NewClient(server, opts...)
	if err != nil {
		return nil, err
	}
	return &ClientWithResponses{client}, nil
}

// WithBaseURL overrides the baseURL.
func WithBaseURL(baseURL string) ClientOption {
	return func(c *Client) error {
		newBaseURL, err := url.Parse(baseURL)
		if err != nil {
			return err
		}
		c.Server = newBaseURL.String()
		return nil
	}
}

// ClientWithResponsesInterface is the interface specification for the client with responses above.
type ClientWithResponsesInterface interface {
	// GetExpectationsWithResponse request
	GetExpectationsWithResponse(ctx context.Context, params *GetExpectationsParams, reqEditors ...RequestEditorFn) (*GetExpectationsResponse, error)

	// CreateExpectationWithBodyWithResponse request with any body
	CreateExpectationWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*CreateExpectationResponse, error)

	CreateExpectationWithResponse(ctx context.Context, body CreateExpectationJSONRequestBody, reqEditors ...RequestEditorFn) (*CreateExpectationResponse, error)

	// GetLogsWithResponse request
	GetLogsWithResponse(ctx context.Context, params *GetLogsParams, reqEditors ...RequestEditorFn) (*GetLogsResponse, error)

	// GetRoutesWithResponse request
	GetRoutesWithResponse(ctx context.Context, reqEditors ...RequestEditorFn) (*GetRoutesResponse, error)
}

type GetExpectationsResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *Expectations
	JSON400      *BadRequest
	JSON500      *InternalServerError
}

// Status returns HTTPResponse.Status
func (r GetExpectationsResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r GetExpectationsResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type CreateExpectationResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON201      *Expectation
	JSON400      *BadRequest
	JSON500      *InternalServerError
}

// Status returns HTTPResponse.Status
func (r CreateExpectationResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r CreateExpectationResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type GetLogsResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON400      *BadRequest
	JSON500      *InternalServerError
}

// Status returns HTTPResponse.Status
func (r GetLogsResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r GetLogsResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type GetRoutesResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *[]Route
	JSON500      *InternalServerError
}

// Status returns HTTPResponse.Status
func (r GetRoutesResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r GetRoutesResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// GetExpectationsWithResponse request returning *GetExpectationsResponse
func (c *ClientWithResponses) GetExpectationsWithResponse(ctx context.Context, params *GetExpectationsParams, reqEditors ...RequestEditorFn) (*GetExpectationsResponse, error) {
	rsp, err := c.GetExpectations(ctx, params, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseGetExpectationsResponse(rsp)
}

// CreateExpectationWithBodyWithResponse request with arbitrary body returning *CreateExpectationResponse
func (c *ClientWithResponses) CreateExpectationWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*CreateExpectationResponse, error) {
	rsp, err := c.CreateExpectationWithBody(ctx, contentType, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseCreateExpectationResponse(rsp)
}

func (c *ClientWithResponses) CreateExpectationWithResponse(ctx context.Context, body CreateExpectationJSONRequestBody, reqEditors ...RequestEditorFn) (*CreateExpectationResponse, error) {
	rsp, err := c.CreateExpectation(ctx, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseCreateExpectationResponse(rsp)
}

// GetLogsWithResponse request returning *GetLogsResponse
func (c *ClientWithResponses) GetLogsWithResponse(ctx context.Context, params *GetLogsParams, reqEditors ...RequestEditorFn) (*GetLogsResponse, error) {
	rsp, err := c.GetLogs(ctx, params, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseGetLogsResponse(rsp)
}

// GetRoutesWithResponse request returning *GetRoutesResponse
func (c *ClientWithResponses) GetRoutesWithResponse(ctx context.Context, reqEditors ...RequestEditorFn) (*GetRoutesResponse, error) {
	rsp, err := c.GetRoutes(ctx, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseGetRoutesResponse(rsp)
}

// ParseGetExpectationsResponse parses an HTTP response from a GetExpectationsWithResponse call
func ParseGetExpectationsResponse(rsp *http.Response) (*GetExpectationsResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &GetExpectationsResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest Expectations
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 400:
		var dest BadRequest
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON400 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 500:
		var dest InternalServerError
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON500 = &dest

	}

	return response, nil
}

// ParseCreateExpectationResponse parses an HTTP response from a CreateExpectationWithResponse call
func ParseCreateExpectationResponse(rsp *http.Response) (*CreateExpectationResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &CreateExpectationResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 201:
		var dest Expectation
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON201 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 400:
		var dest BadRequest
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON400 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 500:
		var dest InternalServerError
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON500 = &dest

	}

	return response, nil
}

// ParseGetLogsResponse parses an HTTP response from a GetLogsWithResponse call
func ParseGetLogsResponse(rsp *http.Response) (*GetLogsResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &GetLogsResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 400:
		var dest BadRequest
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON400 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 500:
		var dest InternalServerError
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON500 = &dest

	}

	return response, nil
}

// ParseGetRoutesResponse parses an HTTP response from a GetRoutesWithResponse call
func ParseGetRoutesResponse(rsp *http.Response) (*GetRoutesResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &GetRoutesResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest []Route
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 500:
		var dest InternalServerError
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON500 = &dest

	}

	return response, nil
}

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// Retrieve all expectations
	// (GET /v1/dolus/expectations)
	GetExpectations(ctx echo.Context, params GetExpectationsParams) error
	// Create a new expectation
	// (POST /v1/dolus/expectations)
	CreateExpectation(ctx echo.Context) error
	// Retrieve the mock server logs
	// (GET /v1/dolus/logs)
	GetLogs(ctx echo.Context, params GetLogsParams) error
	// Retrieve all mock server routes
	// (GET /v1/dolus/routes)
	GetRoutes(ctx echo.Context) error
}

// ServerInterfaceWrapper converts echo contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler ServerInterface
}

// GetExpectations converts echo context to params.
func (w *ServerInterfaceWrapper) GetExpectations(ctx echo.Context) error {
	var err error

	// Parameter object where we will unmarshal all parameters from the context
	var params GetExpectationsParams
	// ------------- Optional query parameter "expectationType" -------------

	err = runtime.BindQueryParameter("form", true, false, "expectationType", ctx.QueryParams(), &params.ExpectationType)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter expectationType: %s", err))
	}

	// ------------- Optional query parameter "path" -------------

	err = runtime.BindQueryParameter("form", true, false, "path", ctx.QueryParams(), &params.Path)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter path: %s", err))
	}

	// ------------- Optional query parameter "method" -------------

	err = runtime.BindQueryParameter("form", true, false, "method", ctx.QueryParams(), &params.Method)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter method: %s", err))
	}

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.GetExpectations(ctx, params)
	return err
}

// CreateExpectation converts echo context to params.
func (w *ServerInterfaceWrapper) CreateExpectation(ctx echo.Context) error {
	var err error

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.CreateExpectation(ctx)
	return err
}

// GetLogs converts echo context to params.
func (w *ServerInterfaceWrapper) GetLogs(ctx echo.Context) error {
	var err error

	// Parameter object where we will unmarshal all parameters from the context
	var params GetLogsParams
	// ------------- Optional query parameter "lines" -------------

	err = runtime.BindQueryParameter("form", true, false, "lines", ctx.QueryParams(), &params.Lines)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter lines: %s", err))
	}

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.GetLogs(ctx, params)
	return err
}

// GetRoutes converts echo context to params.
func (w *ServerInterfaceWrapper) GetRoutes(ctx echo.Context) error {
	var err error

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.GetRoutes(ctx)
	return err
}

// This is a simple interface which specifies echo.Route addition functions which
// are present on both echo.Echo and echo.Group, since we want to allow using
// either of them for path registration
type EchoRouter interface {
	CONNECT(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	DELETE(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	GET(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	HEAD(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	OPTIONS(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	PATCH(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	POST(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	PUT(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	TRACE(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
}

// RegisterHandlers adds each server route to the EchoRouter.
func RegisterHandlers(router EchoRouter, si ServerInterface) {
	RegisterHandlersWithBaseURL(router, si, "")
}

// Registers handlers, and prepends BaseURL to the paths, so that the paths
// can be served under a prefix.
func RegisterHandlersWithBaseURL(router EchoRouter, si ServerInterface, baseURL string) {

	wrapper := ServerInterfaceWrapper{
		Handler: si,
	}

	router.GET(baseURL+"/v1/dolus/expectations", wrapper.GetExpectations)
	router.POST(baseURL+"/v1/dolus/expectations", wrapper.CreateExpectation)
	router.GET(baseURL+"/v1/dolus/logs", wrapper.GetLogs)
	router.GET(baseURL+"/v1/dolus/routes", wrapper.GetRoutes)

}

// Base64 encoded, gzipped, json marshaled Swagger object
var swaggerSpec = []string{

	"H4sIAAAAAAAC/+xaW2/cNhb+KwS3Dy2gzC3xYiEgwDr2NDHWjo3xGAusNw8c6VhiTYkKSdkeGPPfF4fU",
	"hbp4PGkDLFrkpa4k8twv3zmTZxrJrJA55EbT8JkWTLEMDCj7tHwqIDLMcJmvtwVc1R/xWww6UrzAbzSk",
	"zSeiC4j43ZbnCTEpELMtgMg7Ai0pYiRRYEqVByRiOdkAAW5SUOR0+evxzfmaSEVObq7XlxcTGlCO9L+W",
	"oLY0oDnLgIYUuoLRgOoohYyhYJCXGQ1vaUWMBtTRol8CitLQkGqjeJ7Q3S6gF2BSGe/R7NN6fUUyewr1",
	"QJ16utxxgYpvti9J626PCvlxiQJeXV7jn0/L41N8urHvjtcnn2hA16vjkyUqcfn58/IEv1xerc8uP1/T",
	"gJ4uz5fr5bhiV8ykex1m0t+rT8FM2tGmz31Xf7RR9IHFK/hagjZW8yeWFQI0DW+faQZas8R6VCmpiIyi",
	"UimI6e5LQAslC1CGg6XSHO1rUn0g7u0GA88RMykzJGW6pTpmJwVfS44fw9uGBxqUG4Enl0hqBbqQuYYP",
	"Mt62ROTmN4gM3QX0hAmxYdH9ULhTuOM5aMJIVJ1xYj1yITDwjeJJAgpistlaX2Qyuica1AOooJ9LXigG",
	"RDmTko2MtwG5WZ0HhOUxMTwDWRp0XcfSqTGFi3V0vou3ioTVKnymUsWgTmSZGxrSBepVEaPh4mgW0FIJ",
	"GlpCOpxOtZEKJpHMppG9MvSYz7Jvl3VXHVJqiMmddRq0pqp1/BkmySQgKHZAPi7Xv0yGrhyoM2SIpqpj",
	"vs9jMubXRv8+tX8zbqypCc9JxoXgGiKZx5ps4E4qGFeDa8LzB3kPsceN5wYSUMjOGnhM8JvVOSbmY8qj",
	"dJx0HU8acjN5Nc49zziurape6DdRPWKZYVr8RVPba4FD+VZQKECTa8LyThnVYDA0BhnN80iUcZ3QheJS",
	"cbNtszkGw7jQ+MLJ1b7B7JaWMxNtAEQyv+NJqSzbQdbXDGg4a/LDWbyqBK7/2IIeUpfTU1sH6qzGa04S",
	"vLcZKRULrPaGmVLTcDGb7Yb+jbzy+JOCOxrSv01b3DGtesW0Cbhd4Ek+lhD1VyLgAcRIH5uQTzxBSPHA",
	"RAmYdzGPmAGSutc1gfFE9Cy1T966q/WMtP9Kda4fn42+LXeP6pd+ZAb06U3raURq9v/JvGvvvBQieDEK",
	"nDfdmQMiYvFSNKCeAgzQ0KgSAlqAObM1n9v//hRLUVopDdP3yALys9y8tfQy9kTD+SygGSKN2c4LJppI",
	"GZOYbWk/wnbdxNTDIDkmkRQCIpuMXfipAwIsSkmMrRkzkdXZ96ZJuoJxhSh0PM2aRuWl9iD1oCPfbTcL",
	"Ot24qlj9Bub3n6b7tt1uv1PxdjZgUHnVb5kDb3q2xlweZjO8YnjBtekjfhe12gJKA5l+LU38qrtrYp8p",
	"hcHQy5yOPH5599+PVPaz3IDKmbi2/rPN4K/axDz43YentrnUBbTuQlayXoATncpSxCRjJkoHjYyZNOji",
	"00678sHqIFMOb0YDo29Gsd5lzdYHfPtwXnYgSu2ZqYKlH5drh03HYanTZ7SLeTNYY3rpLPw6iKumsEp2",
	"LyRWTf8YCYQ231+JhKoS7guFeojvxoKrHiSSMfSDoKI5GgWHQIs/5n/HffLffMwyNZsXQ8BXq09yBET0",
	"nFWR73ipcsWYm2RpYD/cJArPuCYG8SFYE4PNTogpELShq8w/e/H9y8Apzbl92TmSl969Q3PKqvNdMwop",
	"HpxGrcS+j6wfBg5CEjy/kw775IZFbrORMY492sKdxdG7fyb4AkfkdnVyfHVGrsuikMrQ/kSdcJOWGztS",
	"nyKJCxndu+Y0dQhqFwxU5pogSSaEfNRkK0tXQHJsOF3MY81RjRFCJtqCGNaHMIJHUNWHSuKLszU5r972",
	"JZYF5FqWKoKJVMm0uqynF2drNz47MzrpA/oASjvB55MZHsD7rOA0pG8n+Mq51kbQ9GHutJ728UYCI43s",
	"VzBRavcsNfxgQhDbVnPTscSLo1ldp8S22oBVS5ltAUHV4NB2Lmwnfsic2eYFpoc4/F3q7TjeaY9MX9y1",
	"7oJX73Z3fQdc6G89MYPramaNvJjN6uiG3NqbFYXAEYrLfPqbdpntTyDHQvQhuZ29hpDxj82lB08hr48R",
	"gS/IfFyQalU2JsnbvdMxDWmkgBkEiz7fOYLqdkP6DUhYu8rT63X/QvLvDnLXYRy9de0Ivw8sJt7ce/Qd",
	"GY8B8hEJ6mPEnSP1wYDqMsuY2tpOaRSHB7BVAHqDAEv0cG7AtiLHIPJxHGNZyeGxvycfVJBmokzlo4NC",
	"PbiEoRLjVbfY5VEN+/SwnpzY4PEHocGG8xuys0vNnvOGgiZR/y/7ot+VDNTd6xWt+fcwSyv+n9Qu/Yw5",
	"aevQj0LRLRTONMP8frlO7AIPmyCQehWTYCVwiEvJbC/uEDzjBmyFYHWNgJjkZbYBhaBGyIQIniOOM5Kk",
	"IAqEMjFsyiSxqywEKDLnRiLWHQUp5yjyAJx0JR9h2P5o+8KPgvbU2K+C7Uj0Osgw8GSmhWB8kKnnlaWr",
	"lLSrsfeL2eLdm9nf3yxm6/k8nM/Co6P/uJXwe8TnJNPJ+xVEwB8gbiZsxL12TujCimnhwTucQKoK86Pd",
	"fkO77S8KhAu2OpXsYy+F3FzyjcDeXarxvdjunYMLJR+4nYMxKFTmGjjbyNI0k7GuVhVVsmii3ZAG40h/",
	"5YT+HqB51ehfhfahY/f02f45i3cW8R92p16kdXvLQTtZNwwPt7Ev5MifARn6oapql9bBWr2owLo95Gpl",
	"OwOH06mQEROp1Cacz/4xs4NURWC4lWqCS4FgVZ23s7rdCfsz6jCMR//ti7aeP4QNiyLQumkRNdORXK3L",
	"OT4dSl05o+4l39i3YlA9777s/hcAAP//z2Q3hIQkAAA=",
}

// GetSwagger returns the content of the embedded swagger specification file
// or error if failed to decode
func decodeSpec() ([]byte, error) {
	zipped, err := base64.StdEncoding.DecodeString(strings.Join(swaggerSpec, ""))
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr, err := gzip.NewReader(bytes.NewReader(zipped))
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}
	var buf bytes.Buffer
	_, err = buf.ReadFrom(zr)
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cached of a decoded swagger spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSwagger returns the Swagger specification corresponding to the generated code
// in this file. The external references of Swagger specification are resolved.
// The logic of resolving external references is tightly connected to "import-mapping" feature.
// Externally referenced files must be embedded in the corresponding golang packages.
// Urls can be supported but this task was out of the scope.
func GetSwagger() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}
