// Code generated by mockery v2.42.3. DO NOT EDIT.

package api

import (
	expectation "github.com/DolusMockServer/dolus/pkg/expectation"
	mock "github.com/stretchr/testify/mock"
)

// MapperMock is an autogenerated mock type for the Mapper type
type MapperMock struct {
	mock.Mock
}

type MapperMock_Expecter struct {
	mock *mock.Mock
}

func (_m *MapperMock) EXPECT() *MapperMock_Expecter {
	return &MapperMock_Expecter{mock: &_m.Mock}
}

// MapCueExpectation provides a mock function with given fields: _a0
func (_m *MapperMock) MapCueExpectation(_a0 expectation.Expectation) (*Expectation, error) {
	ret := _m.Called(_a0)

	if len(ret) == 0 {
		panic("no return value specified for MapCueExpectation")
	}

	var r0 *Expectation
	var r1 error
	if rf, ok := ret.Get(0).(func(expectation.Expectation) (*Expectation, error)); ok {
		return rf(_a0)
	}
	if rf, ok := ret.Get(0).(func(expectation.Expectation) *Expectation); ok {
		r0 = rf(_a0)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*Expectation)
		}
	}

	if rf, ok := ret.Get(1).(func(expectation.Expectation) error); ok {
		r1 = rf(_a0)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MapperMock_MapCueExpectation_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'MapCueExpectation'
type MapperMock_MapCueExpectation_Call struct {
	*mock.Call
}

// MapCueExpectation is a helper method to define mock.On call
//   - _a0 expectation.Expectation
func (_e *MapperMock_Expecter) MapCueExpectation(_a0 interface{}) *MapperMock_MapCueExpectation_Call {
	return &MapperMock_MapCueExpectation_Call{Call: _e.mock.On("MapCueExpectation", _a0)}
}

func (_c *MapperMock_MapCueExpectation_Call) Run(run func(_a0 expectation.Expectation)) *MapperMock_MapCueExpectation_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(expectation.Expectation))
	})
	return _c
}

func (_c *MapperMock_MapCueExpectation_Call) Return(_a0 *Expectation, _a1 error) *MapperMock_MapCueExpectation_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MapperMock_MapCueExpectation_Call) RunAndReturn(run func(expectation.Expectation) (*Expectation, error)) *MapperMock_MapCueExpectation_Call {
	_c.Call.Return(run)
	return _c
}

// MapCueExpectations provides a mock function with given fields: expectations
func (_m *MapperMock) MapCueExpectations(expectations []expectation.Expectation) ([]Expectation, error) {
	ret := _m.Called(expectations)

	if len(ret) == 0 {
		panic("no return value specified for MapCueExpectations")
	}

	var r0 []Expectation
	var r1 error
	if rf, ok := ret.Get(0).(func([]expectation.Expectation) ([]Expectation, error)); ok {
		return rf(expectations)
	}
	if rf, ok := ret.Get(0).(func([]expectation.Expectation) []Expectation); ok {
		r0 = rf(expectations)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]Expectation)
		}
	}

	if rf, ok := ret.Get(1).(func([]expectation.Expectation) error); ok {
		r1 = rf(expectations)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MapperMock_MapCueExpectations_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'MapCueExpectations'
type MapperMock_MapCueExpectations_Call struct {
	*mock.Call
}

// MapCueExpectations is a helper method to define mock.On call
//   - expectations []expectation.Expectation
func (_e *MapperMock_Expecter) MapCueExpectations(expectations interface{}) *MapperMock_MapCueExpectations_Call {
	return &MapperMock_MapCueExpectations_Call{Call: _e.mock.On("MapCueExpectations", expectations)}
}

func (_c *MapperMock_MapCueExpectations_Call) Run(run func(expectations []expectation.Expectation)) *MapperMock_MapCueExpectations_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].([]expectation.Expectation))
	})
	return _c
}

func (_c *MapperMock_MapCueExpectations_Call) Return(_a0 []Expectation, _a1 error) *MapperMock_MapCueExpectations_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MapperMock_MapCueExpectations_Call) RunAndReturn(run func([]expectation.Expectation) ([]Expectation, error)) *MapperMock_MapCueExpectations_Call {
	_c.Call.Return(run)
	return _c
}

// NewMapperMock creates a new instance of MapperMock. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMapperMock(t interface {
	mock.TestingT
	Cleanup(func())
}) *MapperMock {
	mock := &MapperMock{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
