openapi: 3.1.0
x-stoplight:
  id: 6cx0tkgt5vl5x
info:
  title: dolus
  version: '1.0'
servers:
  - url: 'http://localhost:1080'
paths:
  /v1/dolus/expectations:
    get:
      summary: Fetch expectations
      tags: []
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Expectations'
      operationId: get-v1-dolus-expectations
      description: Endpoint is for fetching expectations
    post:
      summary: ''
      operationId: post-v1-dolus-expectations
      responses:
        '201':
          description: Created
      description: ''
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Expectation'
              x-examples:
                Example 1:
                  priority: 0
                  request:
                    path: /store/order/2
                    method: GET
                    body: null
                  response:
                    body:
                      complete: true
                      petId:
                        id:
                          $dolus:
                            task: GenInt32
                          max: 10
                          min: 0
                      status: good day
                    status: 200
                  callback: null
  /v1/dolus/routes:
    get:
      summary: Your GET endpoint
      tags: []
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Route'
                  x-stoplight:
                    id: c7rg1wyygdcpd
      operationId: get-v1-dolus-routes
      x-stoplight:
        id: p628l5j5m3iym
  /v1/dolus/logs:
    get:
      summary: Your GET endpoint
      tags: []
      responses: {}
      operationId: get-v1-dolus-logs
      x-stoplight:
        id: 58wunsu9erbjf
      parameters:
        - schema:
            type: integer
          in: query
          name: lines
          description: number of log lines to return
    parameters: []
  /v1/dolus/logs/ws:
    get:
      summary: Your GET endpoint
      tags: []
      responses: {}
      operationId: get-v1-dolus-logs-ws
      x-stoplight:
        id: r4dqbex0jnbv3
      parameters:
        - schema:
            type: string
          in: query
          name: lines
          description: number of log lines to return
components:
  schemas:
    Expectation:
      type: object
      x-examples:
        Example 1:
          priority: 0
          request:
            path: /store/order/2
            method: GET
            body: null
          response:
            body:
              complete: true
              petId:
                id:
                  $dolus:
                    task: GenInt32
                  max: 10
                  min: 0
              status: good day
            status: 200
          callback: null
      properties:
        priority:
          type: integer
        request:
          $ref: '#/components/schemas/Request'
        response:
          $ref: '#/components/schemas/Response'
        callback:
          $ref: '#/components/schemas/Callback'
      required:
        - priority
        - request
        - response
    Callback:
      title: Callback
      x-stoplight:
        id: 88pslexa9iig4
      type: object
      properties:
        httpMethod:
          type: string
          x-stoplight:
            id: sga8n4vtsftc9
        requestBody:
          type: object
          x-stoplight:
            id: i16x1tfjkkdqr
        url:
          type: string
          x-stoplight:
            id: 0jf69yeem8wup
        timeout:
          type: integer
          x-stoplight:
            id: n09z9dwbm1bcb
      required:
        - httpMethod
        - url
        - timeout
    Request:
      title: Request
      x-stoplight:
        id: a6eclhoj91zdo
      type: object
      properties:
        path:
          type: string
          x-stoplight:
            id: res8jde5x0ow0
        method:
          type: string
          x-stoplight:
            id: 03w9895jscrhl
        body:
          type: object
          x-stoplight:
            id: 6dxspuylc1df9
      required:
        - path
        - method
    Response:
      title: Response
      x-stoplight:
        id: twfgprphk5gad
      type: object
      properties:
        status:
          type: integer
          x-stoplight:
            id: ml6sv6me2m6ml
        body:
          type: object
          x-stoplight:
            id: 82nc0or8edpcl
      required:
        - status
    Expectations:
      title: Expectations
      x-stoplight:
        id: gi4kt1w4nyzy7
      type: object
      properties:
        expectations:
          type: array
          x-stoplight:
            id: zsftd2mz4o9wz
          items:
            $ref: '#/components/schemas/Expectation'
            x-stoplight:
              id: myjab1907zuxc
      required:
        - expectations
    Route:
      title: Route
      x-stoplight:
        id: md0y5oj5v3xqo
      type: object
      properties:
        path:
          type: string
          x-stoplight:
            id: rwojafj1z3xk9
        operation:
          type: string
          x-stoplight:
            id: 4jowjjcwg4v1z
      required:
        - path
        - operation